### ISSUE TITLE
All summoner Dungeons Not working

### ISSUE THREAD

**Issue by gourab1986** [rarity-adventure/rarity-frontend#12]
![iusdgh](https://user-images.githubusercontent.com/52283263/133660496-f5b4cfdf-aaa6-4b38-a9c3-0c74ce0d3bfc.PNG)
the functionality to send all summoners to dungeons in a single click is not working.. Its failing everytime.
![iusdgh](https://user-images.githubusercontent.com/52283263/133660620-c7dec25f-a5a6-4d0f-9247-f768c1a3ac4c.PNG)

**Comment by eabz** [comment]
Please try it again, just submitted a fix
