### ISSUE TITLE
Rarity Adventure is not available

### ISSUE THREAD

**Issue by dac0914** [rarity-adventure/rarity-frontend#13]
![image](https://user-images.githubusercontent.com/90873959/133693244-d927895d-2d99-42ac-bbb4-d4dea2500db6.png)

Website not loading for infinite time

**Comment by dac0914** [comment]
also https://rarityvisualizer.com/, https://www.raritymanifested.com/profile, https://raritymmo.com/, https://rarityextended.com/ 
don't work

**Comment by eabz** [comment]
How many summoners do you have?

Right now https://rarity.game is limited to 150 summoners for a single account. We are in the process of increase it to 1000, but probably will take some days.

**Comment by dac0914** [comment]
can't check right now cause any of website is not available.

**Comment by eabz** [comment]
Just submitted a fix, pls try again.
