### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by jeasonmars** [rarity-adventure/rarity-frontend#14]
Can u update the system can load more token？ My wallet has several hundred... Can not show always loading，and one click adventure and cliam and level up？

**Comment by eabz** [comment]
Just submitted a fix, pls try again.

**Comment by jeasonmars** [comment]
> Just submitted a fix, pls try again.

just tried one click adventure ，only can send 1 bag with 100 summoner ，then the left has to click one by one ， I think it is a bug

**Comment by eabz** [comment]
Should be fixed, can you test it again?
