### ISSUE TITLE
https://www.raritymanifested.com/dungeon works on ethereum mainnet

### ISSUE THREAD

**Issue by dac0914** [rarity-adventure/rarity-frontend#15]
I did a transaction at https://www.raritymanifested.com/dungeon without accidentally changing the chain from the Ethereum mainnet to the Fantom Network, but the transaction proceeded without any instructions to change the chain, and it succeeded without failure. Of course, the gas fee hurt a little more.
If this is not what you intended, I think it should be fixed.

**Comment by eabz** [comment]
Sorry, this is only related to https://rarity.game

**Comment by dac0914** [comment]
Wasn't it linked to the same game?

**Comment by eabz** [comment]
Yes, but different UI Devs.
