### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by Ozaki-Yutaka** [rarity-adventure/rarity-frontend#16]
It has been loading since yesterday.
![image](https://user-images.githubusercontent.com/90921288/133815503-942d7d6d-b770-44ca-9a20-834cae8d46c7.png)

**Comment by eabz** [comment]
Just submitted a fix, pls try again.

**Comment by jeasonmars** [comment]
just tried ， 500 nft already 15 mins can not show ，200 work

**Comment by jeasonmars** [comment]
> Just submitted a fix, pls try again.
just tried ， 500 nft already 15 mins can not show ，200 work

**Comment by jeasonmars** [comment]
just tried one click adventure ，only can send 1 bag with 100 summoner ，then the left has to click one by one ， I think it is a bug

**Comment by eabz** [comment]
Yes, thanks, should be fixed now.
